## Put your auth key here (found at http://getfirewind.com/services)
## Must be correct for the server to boot up
auth.key=deadbeefdeadbeefdeadbeefdeadbeef

## MySQL Configuration
db.hostname=localhost
db.port=3306
db.username=root
db.password=
db.name=firewind

## MySQL pooling setup (controls amount of connections)
db.pool.minsize=100
db.pool.maxsize=200

## Game TCP/IP Configuration
game.tcp.bindip=0.0.0.0
game.tcp.port=30000
game.tcp.conlimit=11000
game.tcp.conperip=100
game.tcp.enablenagles=False

## MUS TCP/IP Configuration
mus.tcp.bindip=127.0.0.1
mus.tcp.port=30001
mus.tcp.allowedaddr=localhost;127.0.0.1;localhost

## Client configuration
client.ping.enabled=1
client.ping.interval=20000
client.maxrequests=1000

## In-game features
# Link to friendstream imager (to make heads appear)
game.friendstream.imagerurl=http://yourhotel.com/stream-imager/{0}.gif

#Says wether the users should receive pixels each X seconds, how much and when (When in seconds)
game.pixel.enabled=false
game.pixel.amount=100
game.pixel.time=1200

#Says wether the users should receive pixels each X seconds, how much and when (When in seconds)
game.credits.enabled=false
game.credits.amount=100
game.credits.time=1200

game.login.credits.receiveamount=1
game.login.pixel.receiveamount=1

## Rentable bot configuration
catalog.rentablebots.enabled=true
catalog.rentablebots.default.duration=604800
catalog.rentablebots.default.name=Jon
catalog.rentablebots.default.motto=
catalog.rentablebots.default.figure=hr-3020-34.hd-3091-2.ch-225-92.lg-3058-100.sh-3089-1338.ca-3084-78-108.wa-2005
catalog.rentablebots.default.gender=M

## Advanced settings
SeparatedTasksInMainLoops.enabled=true
SeparatedTasksInGameClientManager.enabled=false
spambans.enabled=false
spambans.limit=20
# How often user count etc will be updated in db (in ms)
backgroundworker.interval=10000
