<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Firewind Emulator</AssemblyName>
    <RootNamespace>Firewind</RootNamespace>
    <StartupObject>Firewind.Program</StartupObject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <NoWarn>$(NoWarn);SYSLIB0003;SYSLIB0014</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="**/* 2.cs" />
    <Compile Remove="Database/Database_Manager/Database/DatabaseClient.cs" />
    <Compile Remove="HabboHotel/Navigators/NavigatorCache.cs" />
    <Compile Remove="HabboHotel/Rooms/AStar/IPathNodeContianer.cs" />
    <Compile Remove="HabboHotel/Rooms/Wired/WiredHandlers/Repeater.cs" />
    <Compile Remove="HabboHotel/SoundMachine/Song.cs" />
    <Compile Remove="HabboHotel/SoundMachine/SoundMachineManager.cs" />
    <Compile Remove="HabboHotel/SoundMachine/SoundTemplate.cs" />
    <Compile Remove="HabboHotel/SoundMachine/SoundTemplateFactory.cs" />
    <Compile Remove="MainServerConnectionHandeling/**/*.cs" />
    <Compile Remove="Messages/ClientMessage.cs" />
    <Compile Remove="QueuedPacketsStuff/**/*.cs" />
    <Compile Remove="Storage/**/*.cs" />
  </ItemGroup>
</Project>
